---
title: "Guide to the mSigAct web server"
author: "Steve Rozen and Nanhai Jiang"
output:
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The mSigAct web server provides methods for analyzing mutational 
signatures. "mSigAct" is an abbreviation of <big><strong>m</strong></big>utational 
<big><strong>Sig</strong></big>nature <big><strong>Act</strong></big>ivity. 

A mutational signature is the pattern of mutations generated by a particular 
mutational process. Examples include the mutations from CG to TG caused
by deamination of 5-methyl cytosine, insertions or deletions in homopolymers
which are common in tumors with DNA-mismatch repair deficiency, or CC to TT mutations
stemming from ultraviolet-radiation-induced pyrimidine dimers.

mSigAct deals with mutational signatures that are defined over various classes
of mutations that are now conventional in the field.
These consist of single-base-pair mutations in the context of preceding
and following bases ("single base substitutions", SBSs), 
various categories of small insertions and deletions (indels), and
"doublet base substitutions" (DBSs).

### TO DO -- can use nature paper figures?

mSigAct has two main groups of functions. 

## Creat and plot mutational spectrum catalogs from from variant call files

One group of functions transforms variant call files (VCFs) into 
mutational spectra and provides 
functionality to plot these or further analyze them.

## Estimate which mutational signatures contributed to a mutational spectrum

The other group of functions deals with inferring mutational signature _activities_ in
individual mutational spectra. By "mutational signature activities
we refer to the numbers of mutations generated by each
mutational signature (or more precisely, generated by each
mutational process)

## Code availability

The mSigAct web front-end code is available at XXXXXX and is released under the GPL3 ]
open source license. Other code used by the mSigAct web
server include mSigAct XXXXXXX, ICAMS, XXXXXX, ICAMSxtra XXXXX, and PCAWG7 XXXXXXX, all released
under the GPL3 open source license.


